### ISSUE TITLE
Install problems

### ISSUE THREAD

**Issue by rgieseke** [gidden/aneris#10]
Hi @gidden 

I just helped a colleague to install this in a Conda environment.
We ended with a local install from a Git clone.

I think https://github.com/gidden/aneris/blob/dcf6679334f44067f376f2fe696e55bf689f2cfb/requirements.txt#L1 should not mention the `aneris` package -- it is unrelated, isn't it?

Is this Python2 only? PyPI only has a Python2 version it seems.

Is this available in some conda forge?

**Comment by gidden** [comment]
Hey Robert - all good points. I've been needing to revisit this and update
all the CI/install infrastructure. Thanks for pointing it out!

**Comment by gidden** [comment]
closing in favor of iiasa/aneris#7
